/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CurrencyFiatDto
    /// </summary>
    [DataContract]
    public partial class CurrencyFiatDto :  IEquatable<CurrencyFiatDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyFiatDto" /> class.
        /// </summary>
        /// <param name="code">The currency code..</param>
        /// <param name="depositFee">The % fee to deposit the currency..</param>
        /// <param name="fiat">Is a fiat currency. (default to true).</param>
        /// <param name="icon">The icon of the currency..</param>
        /// <param name="id">The ID of the currency..</param>
        /// <param name="name">The currency name..</param>
        /// <param name="options">The currency options..</param>
        /// <param name="pricePrecision">The precision of decimal points for the currency. (default to 2).</param>
        /// <param name="protocols">The alternative protocols array..</param>
        /// <param name="quantityPrecision">The precision of decimal points for the currency displayed. (default to 2).</param>
        /// <param name="supportsDeposits">Is deposits for this currency supported. (default to true).</param>
        /// <param name="supportsWithdrawals">Is withdrawals for this currency supported (default to true).</param>
        /// <param name="withdrawalFee">The % fee to withdraw this currency..</param>
        /// <param name="withdrawalParameters">The withdrawal parameter object..</param>
        public CurrencyFiatDto(string code = default(string), decimal depositFee = default(decimal), bool fiat = true, string icon = default(string), long id = default(long), string name = default(string), Object options = default(Object), int pricePrecision = 2, List<Object> protocols = default(List<Object>), int quantityPrecision = 2, bool supportsDeposits = true, bool supportsWithdrawals = true, decimal withdrawalFee = default(decimal), List<Object> withdrawalParameters = default(List<Object>))
        {
            this.Code = code;
            this.DepositFee = depositFee;
            // use default value if no "fiat" provided
            if (fiat == null)
            {
                this.Fiat = true;
            }
            else
            {
                this.Fiat = fiat;
            }
            this.Icon = icon;
            this.Id = id;
            this.Name = name;
            this.Options = options;
            // use default value if no "pricePrecision" provided
            if (pricePrecision == null)
            {
                this.PricePrecision = 2;
            }
            else
            {
                this.PricePrecision = pricePrecision;
            }
            this.Protocols = protocols;
            // use default value if no "quantityPrecision" provided
            if (quantityPrecision == null)
            {
                this.QuantityPrecision = 2;
            }
            else
            {
                this.QuantityPrecision = quantityPrecision;
            }
            // use default value if no "supportsDeposits" provided
            if (supportsDeposits == null)
            {
                this.SupportsDeposits = true;
            }
            else
            {
                this.SupportsDeposits = supportsDeposits;
            }
            // use default value if no "supportsWithdrawals" provided
            if (supportsWithdrawals == null)
            {
                this.SupportsWithdrawals = true;
            }
            else
            {
                this.SupportsWithdrawals = supportsWithdrawals;
            }
            this.WithdrawalFee = withdrawalFee;
            this.WithdrawalParameters = withdrawalParameters;
        }

        /// <summary>
        /// The currency code.
        /// </summary>
        /// <value>The currency code.</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// The % fee to deposit the currency.
        /// </summary>
        /// <value>The % fee to deposit the currency.</value>
        [DataMember(Name="depositFee", EmitDefaultValue=false)]
        public decimal DepositFee { get; set; }

        /// <summary>
        /// Is a fiat currency.
        /// </summary>
        /// <value>Is a fiat currency.</value>
        [DataMember(Name="fiat", EmitDefaultValue=false)]
        public bool Fiat { get; set; }

        /// <summary>
        /// The icon of the currency.
        /// </summary>
        /// <value>The icon of the currency.</value>
        [DataMember(Name="icon", EmitDefaultValue=false)]
        public string Icon { get; set; }

        /// <summary>
        /// The ID of the currency.
        /// </summary>
        /// <value>The ID of the currency.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long Id { get; set; }

        /// <summary>
        /// The currency name.
        /// </summary>
        /// <value>The currency name.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The currency options.
        /// </summary>
        /// <value>The currency options.</value>
        [DataMember(Name="options", EmitDefaultValue=false)]
        public Object Options { get; set; }

        /// <summary>
        /// The precision of decimal points for the currency.
        /// </summary>
        /// <value>The precision of decimal points for the currency.</value>
        [DataMember(Name="pricePrecision", EmitDefaultValue=false)]
        public int PricePrecision { get; set; }

        /// <summary>
        /// The alternative protocols array.
        /// </summary>
        /// <value>The alternative protocols array.</value>
        [DataMember(Name="protocols", EmitDefaultValue=false)]
        public List<Object> Protocols { get; set; }

        /// <summary>
        /// The precision of decimal points for the currency displayed.
        /// </summary>
        /// <value>The precision of decimal points for the currency displayed.</value>
        [DataMember(Name="quantityPrecision", EmitDefaultValue=false)]
        public int QuantityPrecision { get; set; }

        /// <summary>
        /// Is deposits for this currency supported.
        /// </summary>
        /// <value>Is deposits for this currency supported.</value>
        [DataMember(Name="supportsDeposits", EmitDefaultValue=false)]
        public bool SupportsDeposits { get; set; }

        /// <summary>
        /// Is withdrawals for this currency supported
        /// </summary>
        /// <value>Is withdrawals for this currency supported</value>
        [DataMember(Name="supportsWithdrawals", EmitDefaultValue=false)]
        public bool SupportsWithdrawals { get; set; }

        /// <summary>
        /// The % fee to withdraw this currency.
        /// </summary>
        /// <value>The % fee to withdraw this currency.</value>
        [DataMember(Name="withdrawalFee", EmitDefaultValue=false)]
        public decimal WithdrawalFee { get; set; }

        /// <summary>
        /// The withdrawal parameter object.
        /// </summary>
        /// <value>The withdrawal parameter object.</value>
        [DataMember(Name="withdrawalParameters", EmitDefaultValue=false)]
        public List<Object> WithdrawalParameters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CurrencyFiatDto {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  DepositFee: ").Append(DepositFee).Append("\n");
            sb.Append("  Fiat: ").Append(Fiat).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  PricePrecision: ").Append(PricePrecision).Append("\n");
            sb.Append("  Protocols: ").Append(Protocols).Append("\n");
            sb.Append("  QuantityPrecision: ").Append(QuantityPrecision).Append("\n");
            sb.Append("  SupportsDeposits: ").Append(SupportsDeposits).Append("\n");
            sb.Append("  SupportsWithdrawals: ").Append(SupportsWithdrawals).Append("\n");
            sb.Append("  WithdrawalFee: ").Append(WithdrawalFee).Append("\n");
            sb.Append("  WithdrawalParameters: ").Append(WithdrawalParameters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CurrencyFiatDto);
        }

        /// <summary>
        /// Returns true if CurrencyFiatDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CurrencyFiatDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CurrencyFiatDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.DepositFee == input.DepositFee ||
                    (this.DepositFee != null &&
                    this.DepositFee.Equals(input.DepositFee))
                ) && 
                (
                    this.Fiat == input.Fiat ||
                    (this.Fiat != null &&
                    this.Fiat.Equals(input.Fiat))
                ) && 
                (
                    this.Icon == input.Icon ||
                    (this.Icon != null &&
                    this.Icon.Equals(input.Icon))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Options == input.Options ||
                    (this.Options != null &&
                    this.Options.Equals(input.Options))
                ) && 
                (
                    this.PricePrecision == input.PricePrecision ||
                    (this.PricePrecision != null &&
                    this.PricePrecision.Equals(input.PricePrecision))
                ) && 
                (
                    this.Protocols == input.Protocols ||
                    this.Protocols != null &&
                    input.Protocols != null &&
                    this.Protocols.SequenceEqual(input.Protocols)
                ) && 
                (
                    this.QuantityPrecision == input.QuantityPrecision ||
                    (this.QuantityPrecision != null &&
                    this.QuantityPrecision.Equals(input.QuantityPrecision))
                ) && 
                (
                    this.SupportsDeposits == input.SupportsDeposits ||
                    (this.SupportsDeposits != null &&
                    this.SupportsDeposits.Equals(input.SupportsDeposits))
                ) && 
                (
                    this.SupportsWithdrawals == input.SupportsWithdrawals ||
                    (this.SupportsWithdrawals != null &&
                    this.SupportsWithdrawals.Equals(input.SupportsWithdrawals))
                ) && 
                (
                    this.WithdrawalFee == input.WithdrawalFee ||
                    (this.WithdrawalFee != null &&
                    this.WithdrawalFee.Equals(input.WithdrawalFee))
                ) && 
                (
                    this.WithdrawalParameters == input.WithdrawalParameters ||
                    this.WithdrawalParameters != null &&
                    input.WithdrawalParameters != null &&
                    this.WithdrawalParameters.SequenceEqual(input.WithdrawalParameters)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.DepositFee != null)
                    hashCode = hashCode * 59 + this.DepositFee.GetHashCode();
                if (this.Fiat != null)
                    hashCode = hashCode * 59 + this.Fiat.GetHashCode();
                if (this.Icon != null)
                    hashCode = hashCode * 59 + this.Icon.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Options != null)
                    hashCode = hashCode * 59 + this.Options.GetHashCode();
                if (this.PricePrecision != null)
                    hashCode = hashCode * 59 + this.PricePrecision.GetHashCode();
                if (this.Protocols != null)
                    hashCode = hashCode * 59 + this.Protocols.GetHashCode();
                if (this.QuantityPrecision != null)
                    hashCode = hashCode * 59 + this.QuantityPrecision.GetHashCode();
                if (this.SupportsDeposits != null)
                    hashCode = hashCode * 59 + this.SupportsDeposits.GetHashCode();
                if (this.SupportsWithdrawals != null)
                    hashCode = hashCode * 59 + this.SupportsWithdrawals.GetHashCode();
                if (this.WithdrawalFee != null)
                    hashCode = hashCode * 59 + this.WithdrawalFee.GetHashCode();
                if (this.WithdrawalParameters != null)
                    hashCode = hashCode * 59 + this.WithdrawalParameters.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
