/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MerchantChannelPaymentDto
    /// </summary>
    [DataContract]
    public partial class MerchantChannelPaymentDto :  IEquatable<MerchantChannelPaymentDto>, IValidatableObject
    {
        /// <summary>
        /// The status of the channel payment.
        /// </summary>
        /// <value>The status of the channel payment.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum DETECTED for value: DETECTED
            /// </summary>
            [EnumMember(Value = "DETECTED")]
            DETECTED = 1,

            /// <summary>
            /// Enum COMPLETE for value: COMPLETE
            /// </summary>
            [EnumMember(Value = "COMPLETE")]
            COMPLETE = 2,

            /// <summary>
            /// Enum UNKNOWN for value: UNKNOWN
            /// </summary>
            [EnumMember(Value = "UNKNOWN")]
            UNKNOWN = 3

        }

        /// <summary>
        /// The status of the channel payment.
        /// </summary>
        /// <value>The status of the channel payment.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantChannelPaymentDto" /> class.
        /// </summary>
        /// <param name="channelId">The ID of the channel..</param>
        /// <param name="merchantId">The merchant ID linked to channel..</param>
        /// <param name="merchantDisplayName">The display name fo the merchant..</param>
        /// <param name="reference">The unique reference of the channel..</param>
        /// <param name="dateCreated">The date and time, encoded into UNIX epoch timestamps. (default to 0).</param>
        /// <param name="lastUpdated">The date and time, encoded into UNIX epoch timestamps. (default to 0).</param>
        /// <param name="status">The status of the channel payment..</param>
        /// <param name="uuid">The uuid fo the channel payment..</param>
        /// <param name="hash">The transaction hash of the channel payment..</param>
        /// <param name="address">The address of the channel..</param>
        /// <param name="tag">The tag of the channel..</param>
        /// <param name="paidCurrency">The currency of the payment..</param>
        /// <param name="displayCurrency">The display currency of the channel..</param>
        /// <param name="walletCurrency">The currency of the wallet linked to the channel..</param>
        /// <param name="feeCurrency">The currency of the fee taken..</param>
        /// <param name="paidAmount">The amount paid to the channel. (default to 0M).</param>
        /// <param name="displayAmount">The amount displayed of the channel payment. (default to 0M).</param>
        /// <param name="walletAmount">The amount converted to the wallet linked to the channel. (default to 0M).</param>
        /// <param name="feeAmount">The amount of the fee taken. (default to 0M).</param>
        /// <param name="exchangeRate">exchangeRate.</param>
        /// <param name="displayRate">displayRate.</param>
        /// <param name="risk">risk.</param>
        /// <param name="sources">The address source of the payment..</param>
        /// <param name="networkFee">networkFee.</param>
        public MerchantChannelPaymentDto(string channelId = default(string), string merchantId = default(string), string merchantDisplayName = default(string), string reference = default(string), long dateCreated = 0, long lastUpdated = 0, StatusEnum? status = default(StatusEnum?), string uuid = default(string), string hash = default(string), string address = default(string), string tag = default(string), string paidCurrency = default(string), string displayCurrency = default(string), string walletCurrency = default(string), string feeCurrency = default(string), decimal paidAmount = 0M, decimal displayAmount = 0M, decimal walletAmount = 0M, decimal feeAmount = 0M, ExchangeRateDto exchangeRate = default(ExchangeRateDto), ExchangeRateDto displayRate = default(ExchangeRateDto), ExchangeRateDto risk = default(ExchangeRateDto), List<string> sources = default(List<string>), NetworkFeeDto networkFee = default(NetworkFeeDto))
        {
            this.ChannelId = channelId;
            this.MerchantId = merchantId;
            this.MerchantDisplayName = merchantDisplayName;
            this.Reference = reference;
            // use default value if no "dateCreated" provided
            if (dateCreated == null)
            {
                this.DateCreated = 0;
            }
            else
            {
                this.DateCreated = dateCreated;
            }
            // use default value if no "lastUpdated" provided
            if (lastUpdated == null)
            {
                this.LastUpdated = 0;
            }
            else
            {
                this.LastUpdated = lastUpdated;
            }
            this.Status = status;
            this.Uuid = uuid;
            this.Hash = hash;
            this.Address = address;
            this.Tag = tag;
            this.PaidCurrency = paidCurrency;
            this.DisplayCurrency = displayCurrency;
            this.WalletCurrency = walletCurrency;
            this.FeeCurrency = feeCurrency;
            // use default value if no "paidAmount" provided
            if (paidAmount == null)
            {
                this.PaidAmount = 0M;
            }
            else
            {
                this.PaidAmount = paidAmount;
            }
            // use default value if no "displayAmount" provided
            if (displayAmount == null)
            {
                this.DisplayAmount = 0M;
            }
            else
            {
                this.DisplayAmount = displayAmount;
            }
            // use default value if no "walletAmount" provided
            if (walletAmount == null)
            {
                this.WalletAmount = 0M;
            }
            else
            {
                this.WalletAmount = walletAmount;
            }
            // use default value if no "feeAmount" provided
            if (feeAmount == null)
            {
                this.FeeAmount = 0M;
            }
            else
            {
                this.FeeAmount = feeAmount;
            }
            this.ExchangeRate = exchangeRate;
            this.DisplayRate = displayRate;
            this.Risk = risk;
            this.Sources = sources;
            this.NetworkFee = networkFee;
        }

        /// <summary>
        /// The ID of the channel.
        /// </summary>
        /// <value>The ID of the channel.</value>
        [DataMember(Name="channelId", EmitDefaultValue=false)]
        public string ChannelId { get; set; }

        /// <summary>
        /// The merchant ID linked to channel.
        /// </summary>
        /// <value>The merchant ID linked to channel.</value>
        [DataMember(Name="merchantId", EmitDefaultValue=false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// The display name fo the merchant.
        /// </summary>
        /// <value>The display name fo the merchant.</value>
        [DataMember(Name="merchantDisplayName", EmitDefaultValue=false)]
        public string MerchantDisplayName { get; set; }

        /// <summary>
        /// The unique reference of the channel.
        /// </summary>
        /// <value>The unique reference of the channel.</value>
        [DataMember(Name="reference", EmitDefaultValue=false)]
        public string Reference { get; set; }

        /// <summary>
        /// The date and time, encoded into UNIX epoch timestamps.
        /// </summary>
        /// <value>The date and time, encoded into UNIX epoch timestamps.</value>
        [DataMember(Name="dateCreated", EmitDefaultValue=false)]
        public long DateCreated { get; set; }

        /// <summary>
        /// The date and time, encoded into UNIX epoch timestamps.
        /// </summary>
        /// <value>The date and time, encoded into UNIX epoch timestamps.</value>
        [DataMember(Name="lastUpdated", EmitDefaultValue=false)]
        public long LastUpdated { get; set; }


        /// <summary>
        /// The uuid fo the channel payment.
        /// </summary>
        /// <value>The uuid fo the channel payment.</value>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public string Uuid { get; set; }

        /// <summary>
        /// The transaction hash of the channel payment.
        /// </summary>
        /// <value>The transaction hash of the channel payment.</value>
        [DataMember(Name="hash", EmitDefaultValue=false)]
        public string Hash { get; set; }

        /// <summary>
        /// The address of the channel.
        /// </summary>
        /// <value>The address of the channel.</value>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public string Address { get; set; }

        /// <summary>
        /// The tag of the channel.
        /// </summary>
        /// <value>The tag of the channel.</value>
        [DataMember(Name="tag", EmitDefaultValue=false)]
        public string Tag { get; set; }

        /// <summary>
        /// The currency of the payment.
        /// </summary>
        /// <value>The currency of the payment.</value>
        [DataMember(Name="paidCurrency", EmitDefaultValue=false)]
        public string PaidCurrency { get; set; }

        /// <summary>
        /// The display currency of the channel.
        /// </summary>
        /// <value>The display currency of the channel.</value>
        [DataMember(Name="displayCurrency", EmitDefaultValue=false)]
        public string DisplayCurrency { get; set; }

        /// <summary>
        /// The currency of the wallet linked to the channel.
        /// </summary>
        /// <value>The currency of the wallet linked to the channel.</value>
        [DataMember(Name="walletCurrency", EmitDefaultValue=false)]
        public string WalletCurrency { get; set; }

        /// <summary>
        /// The currency of the fee taken.
        /// </summary>
        /// <value>The currency of the fee taken.</value>
        [DataMember(Name="feeCurrency", EmitDefaultValue=false)]
        public string FeeCurrency { get; set; }

        /// <summary>
        /// The amount paid to the channel.
        /// </summary>
        /// <value>The amount paid to the channel.</value>
        [DataMember(Name="paidAmount", EmitDefaultValue=false)]
        public decimal PaidAmount { get; set; }

        /// <summary>
        /// The amount displayed of the channel payment.
        /// </summary>
        /// <value>The amount displayed of the channel payment.</value>
        [DataMember(Name="displayAmount", EmitDefaultValue=false)]
        public decimal DisplayAmount { get; set; }

        /// <summary>
        /// The amount converted to the wallet linked to the channel.
        /// </summary>
        /// <value>The amount converted to the wallet linked to the channel.</value>
        [DataMember(Name="walletAmount", EmitDefaultValue=false)]
        public decimal WalletAmount { get; set; }

        /// <summary>
        /// The amount of the fee taken.
        /// </summary>
        /// <value>The amount of the fee taken.</value>
        [DataMember(Name="feeAmount", EmitDefaultValue=false)]
        public decimal FeeAmount { get; set; }

        /// <summary>
        /// Gets or Sets ExchangeRate
        /// </summary>
        [DataMember(Name="exchangeRate", EmitDefaultValue=false)]
        public ExchangeRateDto ExchangeRate { get; set; }

        /// <summary>
        /// Gets or Sets DisplayRate
        /// </summary>
        [DataMember(Name="displayRate", EmitDefaultValue=false)]
        public ExchangeRateDto DisplayRate { get; set; }

        /// <summary>
        /// Gets or Sets Risk
        /// </summary>
        [DataMember(Name="risk", EmitDefaultValue=false)]
        public ExchangeRateDto Risk { get; set; }

        /// <summary>
        /// The address source of the payment.
        /// </summary>
        /// <value>The address source of the payment.</value>
        [DataMember(Name="sources", EmitDefaultValue=false)]
        public List<string> Sources { get; set; }

        /// <summary>
        /// Gets or Sets NetworkFee
        /// </summary>
        [DataMember(Name="networkFee", EmitDefaultValue=false)]
        public NetworkFeeDto NetworkFee { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MerchantChannelPaymentDto {\n");
            sb.Append("  ChannelId: ").Append(ChannelId).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  MerchantDisplayName: ").Append(MerchantDisplayName).Append("\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  DateCreated: ").Append(DateCreated).Append("\n");
            sb.Append("  LastUpdated: ").Append(LastUpdated).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  PaidCurrency: ").Append(PaidCurrency).Append("\n");
            sb.Append("  DisplayCurrency: ").Append(DisplayCurrency).Append("\n");
            sb.Append("  WalletCurrency: ").Append(WalletCurrency).Append("\n");
            sb.Append("  FeeCurrency: ").Append(FeeCurrency).Append("\n");
            sb.Append("  PaidAmount: ").Append(PaidAmount).Append("\n");
            sb.Append("  DisplayAmount: ").Append(DisplayAmount).Append("\n");
            sb.Append("  WalletAmount: ").Append(WalletAmount).Append("\n");
            sb.Append("  FeeAmount: ").Append(FeeAmount).Append("\n");
            sb.Append("  ExchangeRate: ").Append(ExchangeRate).Append("\n");
            sb.Append("  DisplayRate: ").Append(DisplayRate).Append("\n");
            sb.Append("  Risk: ").Append(Risk).Append("\n");
            sb.Append("  Sources: ").Append(Sources).Append("\n");
            sb.Append("  NetworkFee: ").Append(NetworkFee).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MerchantChannelPaymentDto);
        }

        /// <summary>
        /// Returns true if MerchantChannelPaymentDto instances are equal
        /// </summary>
        /// <param name="input">Instance of MerchantChannelPaymentDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MerchantChannelPaymentDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ChannelId == input.ChannelId ||
                    (this.ChannelId != null &&
                    this.ChannelId.Equals(input.ChannelId))
                ) && 
                (
                    this.MerchantId == input.MerchantId ||
                    (this.MerchantId != null &&
                    this.MerchantId.Equals(input.MerchantId))
                ) && 
                (
                    this.MerchantDisplayName == input.MerchantDisplayName ||
                    (this.MerchantDisplayName != null &&
                    this.MerchantDisplayName.Equals(input.MerchantDisplayName))
                ) && 
                (
                    this.Reference == input.Reference ||
                    (this.Reference != null &&
                    this.Reference.Equals(input.Reference))
                ) && 
                (
                    this.DateCreated == input.DateCreated ||
                    (this.DateCreated != null &&
                    this.DateCreated.Equals(input.DateCreated))
                ) && 
                (
                    this.LastUpdated == input.LastUpdated ||
                    (this.LastUpdated != null &&
                    this.LastUpdated.Equals(input.LastUpdated))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Uuid == input.Uuid ||
                    (this.Uuid != null &&
                    this.Uuid.Equals(input.Uuid))
                ) && 
                (
                    this.Hash == input.Hash ||
                    (this.Hash != null &&
                    this.Hash.Equals(input.Hash))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.Tag == input.Tag ||
                    (this.Tag != null &&
                    this.Tag.Equals(input.Tag))
                ) && 
                (
                    this.PaidCurrency == input.PaidCurrency ||
                    (this.PaidCurrency != null &&
                    this.PaidCurrency.Equals(input.PaidCurrency))
                ) && 
                (
                    this.DisplayCurrency == input.DisplayCurrency ||
                    (this.DisplayCurrency != null &&
                    this.DisplayCurrency.Equals(input.DisplayCurrency))
                ) && 
                (
                    this.WalletCurrency == input.WalletCurrency ||
                    (this.WalletCurrency != null &&
                    this.WalletCurrency.Equals(input.WalletCurrency))
                ) && 
                (
                    this.FeeCurrency == input.FeeCurrency ||
                    (this.FeeCurrency != null &&
                    this.FeeCurrency.Equals(input.FeeCurrency))
                ) && 
                (
                    this.PaidAmount == input.PaidAmount ||
                    (this.PaidAmount != null &&
                    this.PaidAmount.Equals(input.PaidAmount))
                ) && 
                (
                    this.DisplayAmount == input.DisplayAmount ||
                    (this.DisplayAmount != null &&
                    this.DisplayAmount.Equals(input.DisplayAmount))
                ) && 
                (
                    this.WalletAmount == input.WalletAmount ||
                    (this.WalletAmount != null &&
                    this.WalletAmount.Equals(input.WalletAmount))
                ) && 
                (
                    this.FeeAmount == input.FeeAmount ||
                    (this.FeeAmount != null &&
                    this.FeeAmount.Equals(input.FeeAmount))
                ) && 
                (
                    this.ExchangeRate == input.ExchangeRate ||
                    (this.ExchangeRate != null &&
                    this.ExchangeRate.Equals(input.ExchangeRate))
                ) && 
                (
                    this.DisplayRate == input.DisplayRate ||
                    (this.DisplayRate != null &&
                    this.DisplayRate.Equals(input.DisplayRate))
                ) && 
                (
                    this.Risk == input.Risk ||
                    (this.Risk != null &&
                    this.Risk.Equals(input.Risk))
                ) && 
                (
                    this.Sources == input.Sources ||
                    this.Sources != null &&
                    input.Sources != null &&
                    this.Sources.SequenceEqual(input.Sources)
                ) && 
                (
                    this.NetworkFee == input.NetworkFee ||
                    (this.NetworkFee != null &&
                    this.NetworkFee.Equals(input.NetworkFee))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChannelId != null)
                    hashCode = hashCode * 59 + this.ChannelId.GetHashCode();
                if (this.MerchantId != null)
                    hashCode = hashCode * 59 + this.MerchantId.GetHashCode();
                if (this.MerchantDisplayName != null)
                    hashCode = hashCode * 59 + this.MerchantDisplayName.GetHashCode();
                if (this.Reference != null)
                    hashCode = hashCode * 59 + this.Reference.GetHashCode();
                if (this.DateCreated != null)
                    hashCode = hashCode * 59 + this.DateCreated.GetHashCode();
                if (this.LastUpdated != null)
                    hashCode = hashCode * 59 + this.LastUpdated.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Uuid != null)
                    hashCode = hashCode * 59 + this.Uuid.GetHashCode();
                if (this.Hash != null)
                    hashCode = hashCode * 59 + this.Hash.GetHashCode();
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.Tag != null)
                    hashCode = hashCode * 59 + this.Tag.GetHashCode();
                if (this.PaidCurrency != null)
                    hashCode = hashCode * 59 + this.PaidCurrency.GetHashCode();
                if (this.DisplayCurrency != null)
                    hashCode = hashCode * 59 + this.DisplayCurrency.GetHashCode();
                if (this.WalletCurrency != null)
                    hashCode = hashCode * 59 + this.WalletCurrency.GetHashCode();
                if (this.FeeCurrency != null)
                    hashCode = hashCode * 59 + this.FeeCurrency.GetHashCode();
                if (this.PaidAmount != null)
                    hashCode = hashCode * 59 + this.PaidAmount.GetHashCode();
                if (this.DisplayAmount != null)
                    hashCode = hashCode * 59 + this.DisplayAmount.GetHashCode();
                if (this.WalletAmount != null)
                    hashCode = hashCode * 59 + this.WalletAmount.GetHashCode();
                if (this.FeeAmount != null)
                    hashCode = hashCode * 59 + this.FeeAmount.GetHashCode();
                if (this.ExchangeRate != null)
                    hashCode = hashCode * 59 + this.ExchangeRate.GetHashCode();
                if (this.DisplayRate != null)
                    hashCode = hashCode * 59 + this.DisplayRate.GetHashCode();
                if (this.Risk != null)
                    hashCode = hashCode * 59 + this.Risk.GetHashCode();
                if (this.Sources != null)
                    hashCode = hashCode * 59 + this.Sources.GetHashCode();
                if (this.NetworkFee != null)
                    hashCode = hashCode * 59 + this.NetworkFee.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
