/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CurrencyFiatDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CurrencyFiatDtoTests
    {
        // TODO uncomment below to declare an instance variable for CurrencyFiatDto
        //private CurrencyFiatDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CurrencyFiatDto
            //instance = new CurrencyFiatDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CurrencyFiatDto
        /// </summary>
        [Test]
        public void CurrencyFiatDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CurrencyFiatDto
            //Assert.IsInstanceOf(typeof(CurrencyFiatDto), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'DepositFee'
        /// </summary>
        [Test]
        public void DepositFeeTest()
        {
            // TODO unit test for the property 'DepositFee'
        }
        /// <summary>
        /// Test the property 'Fiat'
        /// </summary>
        [Test]
        public void FiatTest()
        {
            // TODO unit test for the property 'Fiat'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'PricePrecision'
        /// </summary>
        [Test]
        public void PricePrecisionTest()
        {
            // TODO unit test for the property 'PricePrecision'
        }
        /// <summary>
        /// Test the property 'Protocols'
        /// </summary>
        [Test]
        public void ProtocolsTest()
        {
            // TODO unit test for the property 'Protocols'
        }
        /// <summary>
        /// Test the property 'QuantityPrecision'
        /// </summary>
        [Test]
        public void QuantityPrecisionTest()
        {
            // TODO unit test for the property 'QuantityPrecision'
        }
        /// <summary>
        /// Test the property 'SupportsDeposits'
        /// </summary>
        [Test]
        public void SupportsDepositsTest()
        {
            // TODO unit test for the property 'SupportsDeposits'
        }
        /// <summary>
        /// Test the property 'SupportsWithdrawals'
        /// </summary>
        [Test]
        public void SupportsWithdrawalsTest()
        {
            // TODO unit test for the property 'SupportsWithdrawals'
        }
        /// <summary>
        /// Test the property 'WithdrawalFee'
        /// </summary>
        [Test]
        public void WithdrawalFeeTest()
        {
            // TODO unit test for the property 'WithdrawalFee'
        }
        /// <summary>
        /// Test the property 'WithdrawalParameters'
        /// </summary>
        [Test]
        public void WithdrawalParametersTest()
        {
            // TODO unit test for the property 'WithdrawalParameters'
        }

    }

}
