/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MerchantChannelPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantChannelPaymentTests
    {
        // TODO uncomment below to declare an instance variable for MerchantChannelPayment
        //private MerchantChannelPayment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MerchantChannelPayment
            //instance = new MerchantChannelPayment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MerchantChannelPayment
        /// </summary>
        [Test]
        public void MerchantChannelPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MerchantChannelPayment
            //Assert.IsInstanceOf(typeof(MerchantChannelPayment), instance);
        }


        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Test]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }
        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Test]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }
        /// <summary>
        /// Test the property 'MerchantDisplayName'
        /// </summary>
        [Test]
        public void MerchantDisplayNameTest()
        {
            // TODO unit test for the property 'MerchantDisplayName'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Test]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'PaidCurrency'
        /// </summary>
        [Test]
        public void PaidCurrencyTest()
        {
            // TODO unit test for the property 'PaidCurrency'
        }
        /// <summary>
        /// Test the property 'DisplayCurrency'
        /// </summary>
        [Test]
        public void DisplayCurrencyTest()
        {
            // TODO unit test for the property 'DisplayCurrency'
        }
        /// <summary>
        /// Test the property 'WalletCurrency'
        /// </summary>
        [Test]
        public void WalletCurrencyTest()
        {
            // TODO unit test for the property 'WalletCurrency'
        }
        /// <summary>
        /// Test the property 'FeeCurrency'
        /// </summary>
        [Test]
        public void FeeCurrencyTest()
        {
            // TODO unit test for the property 'FeeCurrency'
        }
        /// <summary>
        /// Test the property 'PaidAmount'
        /// </summary>
        [Test]
        public void PaidAmountTest()
        {
            // TODO unit test for the property 'PaidAmount'
        }
        /// <summary>
        /// Test the property 'DisplayAmount'
        /// </summary>
        [Test]
        public void DisplayAmountTest()
        {
            // TODO unit test for the property 'DisplayAmount'
        }
        /// <summary>
        /// Test the property 'WalletAmount'
        /// </summary>
        [Test]
        public void WalletAmountTest()
        {
            // TODO unit test for the property 'WalletAmount'
        }
        /// <summary>
        /// Test the property 'FeeAmount'
        /// </summary>
        [Test]
        public void FeeAmountTest()
        {
            // TODO unit test for the property 'FeeAmount'
        }
        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Test]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }
        /// <summary>
        /// Test the property 'DisplayRate'
        /// </summary>
        [Test]
        public void DisplayRateTest()
        {
            // TODO unit test for the property 'DisplayRate'
        }
        /// <summary>
        /// Test the property 'Risk'
        /// </summary>
        [Test]
        public void RiskTest()
        {
            // TODO unit test for the property 'Risk'
        }
        /// <summary>
        /// Test the property 'Sources'
        /// </summary>
        [Test]
        public void SourcesTest()
        {
            // TODO unit test for the property 'Sources'
        }
        /// <summary>
        /// Test the property 'NetworkFee'
        /// </summary>
        [Test]
        public void NetworkFeeTest()
        {
            // TODO unit test for the property 'NetworkFee'
        }

    }

}
