/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PayInInstruction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayInInstructionTests
    {
        // TODO uncomment below to declare an instance variable for PayInInstruction
        //private PayInInstruction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayInInstruction
            //instance = new PayInInstruction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayInInstruction
        /// </summary>
        [Test]
        public void PayInInstructionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PayInInstruction
            //Assert.IsInstanceOf(typeof(PayInInstruction), instance);
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Form'
        /// </summary>
        [Test]
        public void FormTest()
        {
            // TODO unit test for the property 'Form'
        }
        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Test]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }
        /// <summary>
        /// Test the property 'DisplayParameters'
        /// </summary>
        [Test]
        public void DisplayParametersTest()
        {
            // TODO unit test for the property 'DisplayParameters'
        }

    }

}
