/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PayInMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayInMethodTests
    {
        // TODO uncomment below to declare an instance variable for PayInMethod
        //private PayInMethod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayInMethod
            //instance = new PayInMethod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayInMethod
        /// </summary>
        [Test]
        public void PayInMethodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PayInMethod
            //Assert.IsInstanceOf(typeof(PayInMethod), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'SettlementCurrency'
        /// </summary>
        [Test]
        public void SettlementCurrencyTest()
        {
            // TODO unit test for the property 'SettlementCurrency'
        }
        /// <summary>
        /// Test the property 'RequestedCurrency'
        /// </summary>
        [Test]
        public void RequestedCurrencyTest()
        {
            // TODO unit test for the property 'RequestedCurrency'
        }
        /// <summary>
        /// Test the property 'EstimatedExchangeRate'
        /// </summary>
        [Test]
        public void EstimatedExchangeRateTest()
        {
            // TODO unit test for the property 'EstimatedExchangeRate'
        }
        /// <summary>
        /// Test the property 'AccountMethods'
        /// </summary>
        [Test]
        public void AccountMethodsTest()
        {
            // TODO unit test for the property 'AccountMethods'
        }

    }

}
