/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PayRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayRequestDtoTests
    {
        // TODO uncomment below to declare an instance variable for PayRequestDto
        //private PayRequestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PayRequestDto
            //instance = new PayRequestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayRequestDto
        /// </summary>
        [Test]
        public void PayRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PayRequestDto
            //Assert.IsInstanceOf(typeof(PayRequestDto), instance);
        }


        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Test]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'ExpiryMinutes'
        /// </summary>
        [Test]
        public void ExpiryMinutesTest()
        {
            // TODO unit test for the property 'ExpiryMinutes'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Test]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'PayInDetails'
        /// </summary>
        [Test]
        public void PayInDetailsTest()
        {
            // TODO unit test for the property 'PayInDetails'
        }
        /// <summary>
        /// Test the property 'PayOutDetails'
        /// </summary>
        [Test]
        public void PayOutDetailsTest()
        {
            // TODO unit test for the property 'PayOutDetails'
        }

    }

}
