/*
 * BVNK API Endpoints
 *
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TransactionReportRequestDataDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionReportRequestDataDtoTests
    {
        // TODO uncomment below to declare an instance variable for TransactionReportRequestDataDto
        //private TransactionReportRequestDataDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionReportRequestDataDto
            //instance = new TransactionReportRequestDataDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionReportRequestDataDto
        /// </summary>
        [Test]
        public void TransactionReportRequestDataDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransactionReportRequestDataDto
            //Assert.IsInstanceOf(typeof(TransactionReportRequestDataDto), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ExternalProcessing'
        /// </summary>
        [Test]
        public void ExternalProcessingTest()
        {
            // TODO unit test for the property 'ExternalProcessing'
        }
        /// <summary>
        /// Test the property 'WalletId'
        /// </summary>
        [Test]
        public void WalletIdTest()
        {
            // TODO unit test for the property 'WalletId'
        }
        /// <summary>
        /// Test the property 'TransactionType'
        /// </summary>
        [Test]
        public void TransactionTypeTest()
        {
            // TODO unit test for the property 'TransactionType'
        }
        /// <summary>
        /// Test the property 'FromDate'
        /// </summary>
        [Test]
        public void FromDateTest()
        {
            // TODO unit test for the property 'FromDate'
        }
        /// <summary>
        /// Test the property 'ToDate'
        /// </summary>
        [Test]
        public void ToDateTest()
        {
            // TODO unit test for the property 'ToDate'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'LanguageTag'
        /// </summary>
        [Test]
        public void LanguageTagTest()
        {
            // TODO unit test for the property 'LanguageTag'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'Include'
        /// </summary>
        [Test]
        public void IncludeTest()
        {
            // TODO unit test for the property 'Include'
        }
        /// <summary>
        /// Test the property 'Exclude'
        /// </summary>
        [Test]
        public void ExcludeTest()
        {
            // TODO unit test for the property 'Exclude'
        }

    }

}
